### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [Hedlen/awesome-segment-anything#17]
Thanks for meticulously maintaining this repository!

We would like to recommend our recent work on "Segment Any Point Cloud Sequences". 

We introduce **Seal**, a framework capable of leveraging 2D vision foundation models for self-supervised learning on large-scale 3D point clouds.

![Seal](https://github.com/youquanl/Segment-Any-Point-Cloud/raw/main/docs/figs/demo.gif)

- Paper: https://arxiv.org/abs/2306.09347
- Code: https://github.com/youquanl/Segment-Any-Point-Cloud
- Project Page: https://ldkong.com/Seal

Thanks a lot!

**Comment by Hedlen** [comment]
@ldkong1205 I have added your nice work. Thanks for your reminder.

**Comment by ldkong1205** [comment]
> @ldkong1205 I have added your nice work. Thanks for your reminder.

Thanks for your help!

**Comment by ldkong1205** [comment]
Thanks for your help!
