### ISSUE TITLE
Segment anything with CLIP's explainability

### ISSUE THREAD

**Issue by Eli-YiLi** [Hedlen/awesome-segment-anything#2]
Thank you for collecting these projects. Nice job!

There is another work about SAM based on CLIP's explainability to achieve text to mask without manual points.
https://github.com/xmed-lab/CLIP_Surgery

Besides, it enhances many open-vocabulary tasks, like segmentation, multi-label classification, multimodal visualization.
This is the jupyter demo:
https://github.com/xmed-lab/CLIP_Surgery/blob/master/demo.ipynb

This is our segmentation results with SAM:
![image](https://user-images.githubusercontent.com/49093246/232215782-3caac15b-e646-4bde-8b1d-ffedb96f20a1.png)

**Comment by Hedlen** [comment]
@Eli-YiLi Thank you for your recognition of my work. I will add the task you mentioned.
