### ISSUE TITLE
Could you kindly include MobileSAM?

### ISSUE THREAD

**Issue by ChaoningZhang** [Hedlen/awesome-segment-anything#22]
We have made a new project to make SAM lightweight for mobile applications.
Could you please kindly include it here?
The link is as follows:
https://github.com/Hedlen/awesome-segment-anything/issues/new

Thanks for your help in advance.

**Comment by Hedlen** [comment]
@ChaoningZhang Thanks for your reminder. I'm very happy to be able to add your excellent work.

**Comment by dangkhoasdc** [comment]
@Hedlen Please help to review and merge it #23

**Comment by Hedlen** [comment]
@dangkhoasdc OK. I have merged, thanks.

**Comment by dangkhoasdc** [comment]
Thanks @Hedlen , please close the issue when you have time.

**Comment by Hedlen** [comment]
@dangkhoasdc OK, thanks.
