### ISSUE TITLE
Add TomoSAM

### ISSUE THREAD

**Issue by fsemerar** [Hedlen/awesome-segment-anything#25]
Please add to your list the newly created [TomoSAM extension](https://github.com/fsemerar/SlicerTomoSAM) of [3D Slicer](https://www.slicer.org/). Here is [the paper](https://arxiv.org/abs/2306.08609) associated to it, and this is the [video tutorial](https://www.youtube.com/watch?v=4nXCYrvBSjk)

**Comment by Hedlen** [comment]
@fsemerar Thanks for your reminder. I'll add the excellent work you mentioned.

**Comment by Hedlen** [comment]
@fsemerar I have updated the excellent work you mentioned.
