### ISSUE TITLE
Yet another SAM web UI

### ISSUE THREAD

**Issue by Kingfish404** [Hedlen/awesome-segment-anything#3]
A more engineer implement

https://github.com/Kingfish404/segment-anything-webui/

Demo for interactive without backend: https://segment-anything-webui.vercel.app/

**Comment by Hedlen** [comment]
@Kingfish404. Thanks for your reminder.

**Comment by Hedlen** [comment]
@Kingfish404. This webpage (https://segment-anything-webui.vercel.app/) is inaccessible. Please check it, thanks.

**Comment by Kingfish404** [comment]
Sadly, the vercel service has been block by GFW. And the VPN used by Megvii (Cisco if not changed, I also used to intern in Megvii Research rface, last year) also can not accessed. You may need to change to another commercial VPN service.

**Comment by Hedlen** [comment]
@Kingfish404. Alright, I will try to switch to another VPN service. I have added your new implementation of SAM web UI to my code repository.

**Comment by Kingfish404** [comment]
EOL
