### ISSUE TITLE
add SAM-CD

### ISSUE THREAD

**Issue by ggsDing** [Hedlen/awesome-segment-anything#32]
Hi,
could you please consider add this remote sensing project:

https://github.com/ggsDing/SAM-CD

paper link:
http://arxiv.org/abs/2309.01429

**Comment by Hedlen** [comment]
@ggsDing Hi, I'm very happy to add your interesting work. Thanks.

**Comment by Hedlen** [comment]
@ggsDing You can initiate a merge request, and I will add your work. Thank you!

**Comment by ggsDing** [comment]
> @ggsDing You can initiate a merge request, and I will add your work. Thank you!

A merge request was sent. Thanks a lot.

**Comment by Hedlen** [comment]
@ggsDing I have merged. Thanks.
