### ISSUE TITLE
Request for adding DefectSAM

### ISSUE THREAD

**Issue by bozhenhhu** [Hedlen/awesome-segment-anything#34]
Hi,
Could you please consider adding this project?

Segment Anything in Defect Dectection.
paper link:
https://arxiv.org/abs/2311.10245

code link:
https://github.com/bozhenhhu/DefectSAM

**Comment by Hedlen** [comment]
@bozhenhhu  Hi, Thanks for your excellent work. You can initiate a merge request, and I will add your work. Thank you!

**Comment by bozhenhhu** [comment]
Thanks; I have pulled and merged a request.

**Comment by Hedlen** [comment]
@bozhenhhu I have merged. Thanks.

**Comment by Hedlen** [comment]
@bozhenhhu I have merged. Thanks.
