### ISSUE TITLE
You may want to add SAMPro3D

### ISSUE THREAD

**Issue by mutianxu** [Hedlen/awesome-segment-anything#37]
Hi,

Thanks for your great repo!

Could you please add our [SAMPro3D](https://mutianxu.github.io/sampro3d/) into the 3D category?

It lifts SAM to 3D indoor scene segmentation, and does not require any training, tuning, or distillation. It achieves superior segmentation results.

Thanks a lot!

**Comment by Hedlen** [comment]
@mutianxu Hi, Thanks for your excellent work. You can initiate a merge request, and I will add your work. Thank you!

**Comment by mutianxu** [comment]
> @mutianxu Hi, Thanks for your excellent work. You can initiate a merge request, and I will add your work. Thank you!

Hi @Hedlen , I have sent a pull request.

Thanks for your help!
