### ISSUE TITLE
How to finetune the SAM on my custom dataset?

### ISSUE THREAD

**Issue by lastwhisper-ghy** [Hedlen/awesome-segment-anything#39]
How to finetune the SAM on my custom dataset?

**Comment by Hedlen** [comment]
@lastwhisper-ghy Hi, you can refer to Sam's original paper and modify it with your custom dataset. Nowadays, many papers also make fine-tuning adjustments to Sam, making the fine-tuned version of Sam more suitable for specific domain applications. In my awesome list, I have also included some articles for you to check.

**Comment by Hedlen** [comment]
@lastwhisper-ghy No worry.
