### ISSUE TITLE
Nanosam C++ Implementation

### ISSUE THREAD

**Issue by spacewalk01** [Hedlen/awesome-segment-anything#42]
Implemented NanoSAM in cpp on Windows for real time segment anything applications:
https://github.com/spacewalk01/nanosam-cpp

**Comment by Hedlen** [comment]
Hi, @spacewalk01 
Thank you for your interest in my work! You can add your work to the repository and submit a pull request. I will review it and merge it into the main branch. Thank you!

**Comment by Hedlen** [comment]
@spacewalk01 I have merged, thanks again.
