### ISSUE TITLE
adding code link of Medical Sam Adapter

### ISSUE THREAD

**Issue by WuJunde** [Hedlen/awesome-segment-anything#47]
Thank you for your great collection!

I am the author of the paper "Medical SAM Adapter", and our code can actually be found at: https://github.com/KidsWithTokens/Medical-SAM-Adapter

It would be appreciated if you could add our code link, thank you very much.

**Comment by Hedlen** [comment]
Hi, @WuJunde Thank you for your interest in my work! You can add your work to the repository and submit a pull request. I will review it and merge it into the main branch. Thank you!

**Comment by Hedlen** [comment]
@WuJunde I have updated your code link, thanks.
