### ISSUE TITLE
SAM application in Robotics

### ISSUE THREAD

**Issue by SiyuanHuang95** [Hedlen/awesome-segment-anything#9]
Hi, thanks for your great work, very inspired 👍 

Besides, I would like to draw your attention to one SAM application in the robotic field:

[Instruct2Act: Mapping Multi-modality Instructions to Robotic Actions with Large Language Model](https://arxiv.org/pdf/2305.11176.pdf)

, where SAM is applied to obtain corresponding masks. The code is also open-sourced at https://github.com/OpenGVLab/Instruct2Act.

**Comment by Hedlen** [comment]
@SiyuanHuang95 Thanks for your reminder. I have added your great work, it's a very interesting application.

**Comment by SiyuanHuang95** [comment]
Thanks for your adding!
